enum data_type {
    BOOLEAN,
    ENUMERATION,
    INTEGER,
    UNSIGNED,
    FLOATING_POINT_NUMBER,
    BIT_VECTOR,
    LOGIC_VECTOR,
    FIXED_POINT_INTEGER,
    UNSIGNED_FIXED_POINT_INTEGER,
    RECORD,
    POINTER,
    ARRAY,
    STRING
}
